<a href="https://colab.research.google.com/github/anuradha2801/Neucleusteq_Training/blob/main/pythonpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
string_user_input=str(input("Enter your name"))
print(string_user_input)

Enter your nameanu
anu


In [ ]:
num1=45
num2=55
print(num1==num2)
print(num1>num2)
print(num1<num2)
print(num1!=num2)

False
False
True
True


In [ ]:
age=int (input("enter age"))
if(age>18):
  print("You are eligible")
else:
  print("you are not eligible")

enter age20
You are eligible
enter age30
You are eligible


In [ ]:
num=int(input("Num: "))
if(num<10):
  print("1 digit number")
elif(num>9 and num<100):
  print("2 digit number")
else:
  print("number is greater than 99")


Num: 100
number is greater than 99


In [ ]:
list1=(10,91,99,80)
for i in list1:
  print (i)

10
91
99
80


In [ ]:
num=0
while num<5:
  num=num+1
  print("anu")

anu
anu
anu
anu
anu


In [ ]:
#add two numbers
num1=int(input("Num1: "))
num2=int(input("Num2: "))
sum=num1+num2
print(sum)

Num1: 10
Num2: 20
30


In [ ]:
#maximum of two numbers
num1=int(input("Num1: "))
num2=int(input("Num2: "))
if(num1>num2):
  print(num1)
else:
  print(num2)

Num1: 20
Num2: 10
20


In [ ]:
s=str(input("Enter string"))
i=0
j=len(s)-1
while(i<j):
  if(s[i]!=s[j]):
    print("Not palindrome")
    break
  else:
    print("palindrome")
  i=i+1
  j=j-1

Enter stringraksha
Not palindrome


In [ ]:
l="hello anu diya prateeksha muskaan"
a=l.split(" ")
for i in a:
  if(len(i)%2==0):
    print(i)


raksha
prateeksha


In [ ]:
tuple={1,2,3}
for i in tuple:
  print(i)

1
2
3


In [ ]:
list1=[1,2,3,4]
list1.append(5)
print(list1)

[1, 2, 3, 4, 5]


In [ ]:
import numpy as np
a1=np.arange(0,11)
print(type(a1))
print(a1)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
mat=np.full((2,2),99)
mat1=np.full(5,12)
print(mat)
print(mat1)

[[99 99]
 [99 99]]
[12 12 12 12 12]


In [ ]:
#eye-identity matrix create with diagonal element
matrix1=np.eye(2)
print("3*3 Matrix: \n",matrix1)
print("\n")
matrix2=np.eye(2,3)
print("2*3 Matrix: \n",matrix2)
print("\n")
matrix3=np.eye(5,5)
print("5*5 Matrix: \n",matrix3)


3*3 Matrix: 
 [[1. 0.]
 [0. 1.]]


2*3 Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]]


5*5 Matrix: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
ele=np.diag(matrix3)
print(ele)
new2=np.diag([1,2,3])
print(new2)

[1. 1. 1. 1. 1.]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
ran_arr=np.random.rand(4,4)
print(ran_arr)
print("\n")
random_arr=np.random.randn(25)
print(random_arr)
print("\n")
ran_arr=np.random.randint(1,51)
print(ran_arr)

[[0.49035176 0.01555112 0.6840611  0.24034226]
 [0.34656237 0.45845244 0.14170791 0.36101852]
 [0.66679154 0.53124369 0.80955713 0.92869699]
 [0.66498524 0.13096041 0.36379347 0.06856775]]


[ 0.18547686 -0.2123017  -0.40159725  0.5647805   0.45960103 -0.59241044
  0.95910295 -0.15903234  0.80791077  0.3956165  -0.68629473 -1.2038784
  1.76663899  0.28445675  0.58053993 -0.88347059 -0.12514287  0.08080968
 -0.34053325  0.9508552   0.22983924 -0.05232212 -0.84387533 -0.66081682
 -0.07065911]


19


In [ ]:
new=np.full_like(mat,33)
print(new)
new1=np.full_like(mat1,45)
print(new1)

[[33 33]
 [33 33]]
[45 45 45 45 45]


In [ ]:
one=np.ones((3,3))
print(one)
ones1=np.ones(one.shape)
print(ones1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
concat=np.concatenate((a1,a2),axis=0)
print(concat)
new_a3=np.append(a1,a2)
print(new_a3)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
list1=[1,2,3]
list2=[9,8,7]
list3=[]
for i in range(0,len(list1)):
  list3.append(list1[i]+list2[i])
print(list3)

[10, 10, 10]


In [ ]:
a=np.array([1,2,3])
print(a+2)
b=np.array([8,9,3])
print(b-2)
print(a==b)
print(np.sort(b))
print(np.max(b))
print(np.min(b))
print(np.argmin(b))
print(np.min(b))
print(np.mean(b))
print(np.median(b))

[3 4 5]
[6 7 1]
[False False  True]
[3 8 9]
9
3
2
6.666666666666667
8.0


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])
arr=np.hstack([a,b,c])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a=("nitin mom anu raksha")
b=a.split(" ")
for k in b:
 if(k==k[::-1]):
   print(k)


nitin
mom
